# Generated by Django 4.2.7 on 2023-11-15 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('shelters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Withdrawn', 'Withdrawn')], max_length=10)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('last_update_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=200)),
                ('address1', models.CharField(max_length=200)),
                ('address2', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(max_length=200)),
                ('province', models.CharField(max_length=2)),
                ('zip_code', models.CharField(max_length=7)),
                ('num_adults', models.IntegerField()),
                ('num_children', models.IntegerField()),
                ('residence', models.CharField(choices=[('House', 'House'), ('Apartment', 'Apartment'), ('Condo', 'Condo'), ('Townhouse', 'Townhouse'), ('Mobile Home', 'Mobile Home')], max_length=50)),
                ('ownership', models.CharField(choices=[('Own', 'Own'), ('Rent', 'Rent')], max_length=50)),
                ('pet_alone_time', models.TextField(max_length=1000)),
                ('current_pets', models.TextField(max_length=1000)),
                ('daily_routine', models.TextField(max_length=1000)),
                ('expenses', models.TextField(max_length=1000)),
                ('previous_pets', models.TextField(max_length=1000)),
                ('reason', models.TextField(max_length=1000)),
                ('reference_name', models.CharField(max_length=50)),
                ('reference_number', models.CharField(max_length=15)),
                ('reference_email', models.EmailField(max_length=254)),
                ('additional_comments', models.TextField(max_length=1000)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='shelters.pet')),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='accounts.petseeker')),
                ('shelter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='shelters.petshelter')),
            ],
        ),
    ]
