# Generated by Django 4.2.6 on 2023-11-14 09:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_alter_application_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
