# Generated by Django 4.2.5 on 2023-11-15 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shelters", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="petimage",
            name="pet",
        ),
        migrations.DeleteModel(
            name="Pet",
        ),
        migrations.DeleteModel(
            name="PetImage",
        ),
    ]
