# Generated by Django 4.2.6 on 2023-11-14 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0002_alter_pet_pet_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='province',
            field=models.CharField(max_length=2),
        ),
    ]
