# Generated by Django 4.2.7 on 2023-11-15 01:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('shelters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('message_type', models.CharField(blank=True, max_length=30, null=True)),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(max_length=500)),
                ('message_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='contenttypes.contenttype')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='accounts.petseeker')),
                ('shelter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='shelters.petshelter')),
            ],
        ),
    ]
