# Generated by Django 4.2.5 on 2023-11-15 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Chat",
        ),
    ]
