# Generated by Django 4.2.5 on 2023-11-15 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="message_content_type",
            new_name="content_type",
        ),
    ]
