# Generated by Django 4.2.6 on 2023-11-11 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('chats', '0002_remove_message_sender_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='contenttypes.contenttype'),
        ),
    ]
