# Generated by Django 4.2.5 on 2023-11-15 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0003_alter_message_message_content_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="message_type",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
